POST http://localhost:3000/api/product
Content-Type: "application/json"

  {
    "name": "เตาไมโครเวฟ",
    "price": 3290,
    "stock": 18,
    "imageUrl": "/products/product-10.jpg",
    "detail": "เตาไมโครเวฟขนาด 23 ลิตร",
    "categoryId": "2"
  }


####

  GET http://localhost:3000/api/product?searchName=&categoryId=1&sortPrice=
